global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'goip'
    static_configs:
      - targets: ['goip:9090']
    metrics_path: '/metrics'
    scrape_interval: 5s